// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace src.persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004074548_WishlistEventProjection")]
    partial class WishlistEventProjection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Persistence.WishlistOutboxEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<double?>("BudgetEstimate")
                        .HasColumnType("double precision")
                        .HasColumnName("budget_estimate");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("StatusChange")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status_change");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "CreatedAt")
                        .HasDatabaseName("ix_wishlist_events_child_id_created_at");

                    b.ToTable("wishlist_events", (string)null);
                });

            modelBuilder.Entity("Services.LogisticsAssessmentEntity", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("child_id");

                    b.Property<bool>("FallbackUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("fallback_used");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("overall_status");

                    b.Property<string>("RecommendationSetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("recommendation_set_id");

                    b.HasKey("id");

                    b.HasIndex("ChildId", "CheckedAt")
                        .HasDatabaseName("ix_logistics_assessments_child_id_checked_at");

                    b.ToTable("logistics_assessments", (string)null);
                });

            modelBuilder.Entity("Services.NotificationEntity", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("RelatedId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("related_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("id");

                    b.HasIndex("ChildId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_child_id_created_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Services.ProfileSnapshotEntity", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("BehaviorSummary")
                        .HasColumnType("text")
                        .HasColumnName("behavior_summary");

                    b.Property<double?>("BudgetCeiling")
                        .HasColumnType("double precision")
                        .HasColumnName("budget_ceiling");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnrichmentSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("enrichment_source");

                    b.Property<bool>("FallbackUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("fallback_used");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preferences");

                    b.HasKey("id");

                    b.HasIndex("ChildId", "CreatedAt")
                        .HasDatabaseName("ix_profile_snapshots_child_id_created_at");

                    b.ToTable("profile_snapshots", (string)null);
                });

            modelBuilder.Entity("Services.RecommendationSetEntity", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("FallbackUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("fallback_used");

                    b.Property<string>("GenerationSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("generation_source");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<string>("ProfileSnapshotId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("profile_snapshot_id");

                    b.HasKey("id");

                    b.HasIndex("ChildId", "CreatedAt")
                        .HasDatabaseName("ix_recommendations_child_id_created_at");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("Services.WishlistItemEntity", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<double?>("BudgetEstimate")
                        .HasColumnType("double precision")
                        .HasColumnName("budget_estimate");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_type");

                    b.Property<string>("StatusChange")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status_change");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("id");

                    b.HasIndex("ChildId", "CreatedAt")
                        .HasDatabaseName("ix_wishlists_child_id_created_at");

                    b.ToTable("wishlists", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
